### ISSUE TITLE
imgFile?

### ISSUE THREAD

**Issue by chubchubcharles** [agethen/dense-flow#1]
Hi agethen,

I typed in the example command usage and obtained the flow_x_chk0.flow and flow_y_chk0.flow files. I noticed in the src code, "denseFlow_gpu_cv3.cc", that there are no args for "--imgFile".
Has this function been deprecated?

Thanks.

**Comment by agethen** [comment]
Hello charles,

I did indeed remove that functionality at some point, as I was not using it (in my case it was more efficient to keep RGB data as a video file).

However, I see the point in having that functionality :) I will probably add it back over the weekend.
Thanks for bringing it up!

-- Sebastian

**Comment by agethen** [comment]
Hi,
I just restored that functionality with the last update.

Thanks!
-- Sebastian
